## @see: http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 37290 ## 待ち受けポートのデフォルト（※実運用では、jar 起動時に --server.port=XXXXX として上書きすること！）

## セキュリティ関連
security:
  enable-csrf: true
  basic:
    enabled: false

## データベース関連
spring:
  datasource:
    initialize: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msmovie
    username: dummy
    password: dummy
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
